HEARTBEAT_TIMEOUT = 5.0
CONNECT_TIMEOUT = 12.0
DATA_TIMEOUT = 1.0
SNAPSHOT_HZ = 25
MESSAGE_RATES = {"ATTITUDE": 20, "LOCAL_POSITION_NED": 15, "OPTICAL_FLOW_RAD": 20,
                 "OPTICAL_FLOW": 10, "DISTANCE_SENSOR": 15, "SYS_STATUS": 1}
